name: python-daily-task

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  0 9 * * * 
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  checkin:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - uses: actions/checkout@v2

    - name: Install Python3
      run: |
        sudo apt update && \
        sudo apt install python3

    - name: Set env
      run: |
        bash set-env.sh
      env: ${{ secrets }}

    - name: Do Task
      run: |
        python3 main.py

    - uses: gautamkrishnar/keepalive-workflow@master # using the workflow with default settings
